spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eloja
    username: root
    password: teste123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql : true
  hibernate:
    ddl-auto : update